package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private Integer id;
     private Integer questionId;
     private String answer;
     private String qtype;

    public Answers() {
    }

    public Answers(Integer questionId, String answer, String qtype) {
       this.questionId = questionId;
       this.answer = answer;
       this.qtype = qtype;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getQtype() {
        return this.qtype;
    }
    
    public void setQtype(String qtype) {
        this.qtype = qtype;
    }




}


