package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AssignmentResult generated by hbm2java
 */
public class AssignmentResult  implements java.io.Serializable {


     private Integer id;
     private int assignmentId;
     private int marks;
     private Date markedDate;
     private String feedback;
     private int studentId;

    public AssignmentResult() {
    }

    public AssignmentResult(int assignmentId, int marks, Date markedDate, String feedback, int studentId) {
       this.assignmentId = assignmentId;
       this.marks = marks;
       this.markedDate = markedDate;
       this.feedback = feedback;
       this.studentId = studentId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }
    public Date getMarkedDate() {
        return this.markedDate;
    }
    
    public void setMarkedDate(Date markedDate) {
        this.markedDate = markedDate;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }




}


