package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AssignmentSubmission generated by hbm2java
 */
public class AssignmentSubmission  implements java.io.Serializable {


     private Integer id;
     private int submittedBy;
     private Date submissionDate;
     private Date submissionTime;
     private String attachment;
     private String solutionNote;
     private int assignmentId;

    public AssignmentSubmission() {
    }

    public AssignmentSubmission(int submittedBy, Date submissionDate, Date submissionTime, String attachment, String solutionNote, int assignmentId) {
       this.submittedBy = submittedBy;
       this.submissionDate = submissionDate;
       this.submissionTime = submissionTime;
       this.attachment = attachment;
       this.solutionNote = solutionNote;
       this.assignmentId = assignmentId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSubmittedBy() {
        return this.submittedBy;
    }
    
    public void setSubmittedBy(int submittedBy) {
        this.submittedBy = submittedBy;
    }
    public Date getSubmissionDate() {
        return this.submissionDate;
    }
    
    public void setSubmissionDate(Date submissionDate) {
        this.submissionDate = submissionDate;
    }
    public Date getSubmissionTime() {
        return this.submissionTime;
    }
    
    public void setSubmissionTime(Date submissionTime) {
        this.submissionTime = submissionTime;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
    public String getSolutionNote() {
        return this.solutionNote;
    }
    
    public void setSolutionNote(String solutionNote) {
        this.solutionNote = solutionNote;
    }
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }




}


