package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private Integer chatId;
     private Date chatTime;
     private Character chatTopic;

    public Chat() {
    }

    public Chat(Date chatTime, Character chatTopic) {
       this.chatTime = chatTime;
       this.chatTopic = chatTopic;
    }
   
    public Integer getChatId() {
        return this.chatId;
    }
    
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }
    public Date getChatTime() {
        return this.chatTime;
    }
    
    public void setChatTime(Date chatTime) {
        this.chatTime = chatTime;
    }
    public Character getChatTopic() {
        return this.chatTopic;
    }
    
    public void setChatTopic(Character chatTopic) {
        this.chatTopic = chatTopic;
    }




}


