package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String courseId;
     private Program program;
     private String courseName;
     private String preRequisiteId;
     private String coRequisiteId;
     private Integer creditHrs;
     private Integer categoryId;

    public Course() {
    }

	
    public Course(String courseId) {
        this.courseId = courseId;
    }
    public Course(String courseId, Program program, String courseName, String preRequisiteId, String coRequisiteId, Integer creditHrs, Integer categoryId) {
       this.courseId = courseId;
       this.program = program;
       this.courseName = courseName;
       this.preRequisiteId = preRequisiteId;
       this.coRequisiteId = coRequisiteId;
       this.creditHrs = creditHrs;
       this.categoryId = categoryId;
    }
   
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public String getPreRequisiteId() {
        return this.preRequisiteId;
    }
    
    public void setPreRequisiteId(String preRequisiteId) {
        this.preRequisiteId = preRequisiteId;
    }
    public String getCoRequisiteId() {
        return this.coRequisiteId;
    }
    
    public void setCoRequisiteId(String coRequisiteId) {
        this.coRequisiteId = coRequisiteId;
    }
    public Integer getCreditHrs() {
        return this.creditHrs;
    }
    
    public void setCreditHrs(Integer creditHrs) {
        this.creditHrs = creditHrs;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }




}


