package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * CourseCategory generated by hbm2java
 */
public class CourseCategory  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private Character description;

    public CourseCategory() {
    }

    public CourseCategory(String categoryName, Character description) {
       this.categoryName = categoryName;
       this.description = description;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Character getDescription() {
        return this.description;
    }
    
    public void setDescription(Character description) {
        this.description = description;
    }




}


