package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * CourseSection generated by hbm2java
 */
public class CourseSection  implements java.io.Serializable {


     private Integer sectionId;
     private String sectionName;
     private String description;
     private String courseId;

    public CourseSection() {
    }

	
    public CourseSection(String courseId) {
        this.courseId = courseId;
    }
    public CourseSection(String sectionName, String description, String courseId) {
       this.sectionName = sectionName;
       this.description = description;
       this.courseId = courseId;
    }
   
    public Integer getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }




}


