package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * CouseTopic generated by hbm2java
 */
public class CouseTopic  implements java.io.Serializable {


     private Integer topicId;
     private String topicName;
     private int preId;
     private String content;
     private int sectionId;

    public CouseTopic() {
    }

	
    public CouseTopic(int preId, String content, int sectionId) {
        this.preId = preId;
        this.content = content;
        this.sectionId = sectionId;
    }
    public CouseTopic(String topicName, int preId, String content, int sectionId) {
       this.topicName = topicName;
       this.preId = preId;
       this.content = content;
       this.sectionId = sectionId;
    }
   
    public Integer getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }
    public String getTopicName() {
        return this.topicName;
    }
    
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }
    public int getPreId() {
        return this.preId;
    }
    
    public void setPreId(int preId) {
        this.preId = preId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }




}


