package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Finalreport generated by hbm2java
 */
public class Finalreport  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String courseId;
     private int quizSubmissionId;
     private int assinmentSubmissionId;
     private int gradeId;

    public Finalreport() {
    }

    public Finalreport(int studentId, String courseId, int quizSubmissionId, int assinmentSubmissionId, int gradeId) {
       this.studentId = studentId;
       this.courseId = courseId;
       this.quizSubmissionId = quizSubmissionId;
       this.assinmentSubmissionId = assinmentSubmissionId;
       this.gradeId = gradeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public int getQuizSubmissionId() {
        return this.quizSubmissionId;
    }
    
    public void setQuizSubmissionId(int quizSubmissionId) {
        this.quizSubmissionId = quizSubmissionId;
    }
    public int getAssinmentSubmissionId() {
        return this.assinmentSubmissionId;
    }
    
    public void setAssinmentSubmissionId(int assinmentSubmissionId) {
        this.assinmentSubmissionId = assinmentSubmissionId;
    }
    public int getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(int gradeId) {
        this.gradeId = gradeId;
    }




}


