package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ForumPost generated by hbm2java
 */
public class ForumPost  implements java.io.Serializable {


     private Integer id;
     private Integer forumId;
     private String postText;
     private Date postDate;
     private Date postTime;
     private Integer userId;

    public ForumPost() {
    }

    public ForumPost(Integer forumId, String postText, Date postDate, Date postTime, Integer userId) {
       this.forumId = forumId;
       this.postText = postText;
       this.postDate = postDate;
       this.postTime = postTime;
       this.userId = userId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getForumId() {
        return this.forumId;
    }
    
    public void setForumId(Integer forumId) {
        this.forumId = forumId;
    }
    public String getPostText() {
        return this.postText;
    }
    
    public void setPostText(String postText) {
        this.postText = postText;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Date getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


