package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Forum generated by hbm2java
 */
public class Forum  implements java.io.Serializable {


     private Integer forumId;
     private String forumName;
     private String courseId;
     private Date dateCreated;
     private Integer views;
     private Integer comments;
     private Integer createdBy;
     private String details;

    public Forum() {
    }

    public Forum(String forumName, String courseId, Date dateCreated, Integer views, Integer comments, Integer createdBy, String details) {
       this.forumName = forumName;
       this.courseId = courseId;
       this.dateCreated = dateCreated;
       this.views = views;
       this.comments = comments;
       this.createdBy = createdBy;
       this.details = details;
    }
   
    public Integer getForumId() {
        return this.forumId;
    }
    
    public void setForumId(Integer forumId) {
        this.forumId = forumId;
    }
    public String getForumName() {
        return this.forumName;
    }
    
    public void setForumName(String forumName) {
        this.forumName = forumName;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getViews() {
        return this.views;
    }
    
    public void setViews(Integer views) {
        this.views = views;
    }
    public Integer getComments() {
        return this.comments;
    }
    
    public void setComments(Integer comments) {
        this.comments = comments;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


