package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ForumPostReply generated by hbm2java
 */
public class ForumPostReply  implements java.io.Serializable {


     private Integer id;
     private Date onDate;
     private Date onTime;
     private String comment;
     private Integer postId;

    public ForumPostReply() {
    }

    public ForumPostReply(Date onDate, Date onTime, String comment, Integer postId) {
       this.onDate = onDate;
       this.onTime = onTime;
       this.comment = comment;
       this.postId = postId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getOnDate() {
        return this.onDate;
    }
    
    public void setOnDate(Date onDate) {
        this.onDate = onDate;
    }
    public Date getOnTime() {
        return this.onTime;
    }
    
    public void setOnTime(Date onTime) {
        this.onTime = onTime;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }




}


