package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private Integer gradeId;
     private Character letterGrade;
     private String range;
     private String description;

    public Grade() {
    }

    public Grade(Character letterGrade, String range, String description) {
       this.letterGrade = letterGrade;
       this.range = range;
       this.description = description;
    }
   
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
    public Character getLetterGrade() {
        return this.letterGrade;
    }
    
    public void setLetterGrade(Character letterGrade) {
        this.letterGrade = letterGrade;
    }
    public String getRange() {
        return this.range;
    }
    
    public void setRange(String range) {
        this.range = range;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


