package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Help generated by hbm2java
 */
public class Help  implements java.io.Serializable {


     private Integer helpId;
     private int studentId;
     private String topic;
     private int linkId;
     private String scrollDiv;
     private int courseId;

    public Help() {
    }

	
    public Help(int studentId, int linkId, int courseId) {
        this.studentId = studentId;
        this.linkId = linkId;
        this.courseId = courseId;
    }
    public Help(int studentId, String topic, int linkId, String scrollDiv, int courseId) {
       this.studentId = studentId;
       this.topic = topic;
       this.linkId = linkId;
       this.scrollDiv = scrollDiv;
       this.courseId = courseId;
    }
   
    public Integer getHelpId() {
        return this.helpId;
    }
    
    public void setHelpId(Integer helpId) {
        this.helpId = helpId;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public int getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(int linkId) {
        this.linkId = linkId;
    }
    public String getScrollDiv() {
        return this.scrollDiv;
    }
    
    public void setScrollDiv(String scrollDiv) {
        this.scrollDiv = scrollDiv;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }




}


