package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Institute generated by hbm2java
 */
public class Institute  implements java.io.Serializable {


     private Integer instituteId;
     private String instituteName;
     private String instituteAddress;
     private String instituteWebsite;
     private String contactUs;
     private Set<Department> departments = new HashSet<Department>(0);

    public Institute() {
    }

    public Institute(String instituteName, String instituteAddress, String instituteWebsite, String contactUs, Set<Department> departments) {
       this.instituteName = instituteName;
       this.instituteAddress = instituteAddress;
       this.instituteWebsite = instituteWebsite;
       this.contactUs = contactUs;
       this.departments = departments;
    }
   
    public Integer getInstituteId() {
        return this.instituteId;
    }
    
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }
    public String getInstituteName() {
        return this.instituteName;
    }
    
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }
    public String getInstituteAddress() {
        return this.instituteAddress;
    }
    
    public void setInstituteAddress(String instituteAddress) {
        this.instituteAddress = instituteAddress;
    }
    public String getInstituteWebsite() {
        return this.instituteWebsite;
    }
    
    public void setInstituteWebsite(String instituteWebsite) {
        this.instituteWebsite = instituteWebsite;
    }
    public String getContactUs() {
        return this.contactUs;
    }
    
    public void setContactUs(String contactUs) {
        this.contactUs = contactUs;
    }
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


