package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Lesson generated by hbm2java
 */
public class Lesson  implements java.io.Serializable {


     private Integer id;
     private String lessonName;
     private Date dateCreated;
     private Integer createdBy;
     private Integer duration;
     private String attachment;
     private String courseId;
     private Integer preReqId;
     private Integer slideTime;
     private Integer sectionId;
     private Integer topicId;
     private Integer preTopicId;

    public Lesson() {
    }

    public Lesson(String lessonName, Date dateCreated, Integer createdBy, Integer duration, String attachment, String courseId, Integer preReqId, Integer slideTime, Integer sectionId, Integer topicId, Integer preTopicId) {
       this.lessonName = lessonName;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.duration = duration;
       this.attachment = attachment;
       this.courseId = courseId;
       this.preReqId = preReqId;
       this.slideTime = slideTime;
       this.sectionId = sectionId;
       this.topicId = topicId;
       this.preTopicId = preTopicId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLessonName() {
        return this.lessonName;
    }
    
    public void setLessonName(String lessonName) {
        this.lessonName = lessonName;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Integer getPreReqId() {
        return this.preReqId;
    }
    
    public void setPreReqId(Integer preReqId) {
        this.preReqId = preReqId;
    }
    public Integer getSlideTime() {
        return this.slideTime;
    }
    
    public void setSlideTime(Integer slideTime) {
        this.slideTime = slideTime;
    }
    public Integer getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }
    public Integer getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }
    public Integer getPreTopicId() {
        return this.preTopicId;
    }
    
    public void setPreTopicId(Integer preTopicId) {
        this.preTopicId = preTopicId;
    }




}


