package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LessonTimming generated by hbm2java
 */
public class LessonTimming  implements java.io.Serializable {


     private Integer lessonTimingId;
     private String lessonId;
     private String startedTime;
     private Date endTime;

    public LessonTimming() {
    }

	
    public LessonTimming(String lessonId) {
        this.lessonId = lessonId;
    }
    public LessonTimming(String lessonId, String startedTime, Date endTime) {
       this.lessonId = lessonId;
       this.startedTime = startedTime;
       this.endTime = endTime;
    }
   
    public Integer getLessonTimingId() {
        return this.lessonTimingId;
    }
    
    public void setLessonTimingId(Integer lessonTimingId) {
        this.lessonTimingId = lessonTimingId;
    }
    public String getLessonId() {
        return this.lessonId;
    }
    
    public void setLessonId(String lessonId) {
        this.lessonId = lessonId;
    }
    public String getStartedTime() {
        return this.startedTime;
    }
    
    public void setStartedTime(String startedTime) {
        this.startedTime = startedTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


