package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * LessonContent generated by hbm2java
 */
public class LessonContent  implements java.io.Serializable {


     private Integer lessonContentId;
     private int lessonId;
     private int lessonPreRequisiteId;
     private Integer couseId;

    public LessonContent() {
    }

	
    public LessonContent(int lessonId, int lessonPreRequisiteId) {
        this.lessonId = lessonId;
        this.lessonPreRequisiteId = lessonPreRequisiteId;
    }
    public LessonContent(int lessonId, int lessonPreRequisiteId, Integer couseId) {
       this.lessonId = lessonId;
       this.lessonPreRequisiteId = lessonPreRequisiteId;
       this.couseId = couseId;
    }
   
    public Integer getLessonContentId() {
        return this.lessonContentId;
    }
    
    public void setLessonContentId(Integer lessonContentId) {
        this.lessonContentId = lessonContentId;
    }
    public int getLessonId() {
        return this.lessonId;
    }
    
    public void setLessonId(int lessonId) {
        this.lessonId = lessonId;
    }
    public int getLessonPreRequisiteId() {
        return this.lessonPreRequisiteId;
    }
    
    public void setLessonPreRequisiteId(int lessonPreRequisiteId) {
        this.lessonPreRequisiteId = lessonPreRequisiteId;
    }
    public Integer getCouseId() {
        return this.couseId;
    }
    
    public void setCouseId(Integer couseId) {
        this.couseId = couseId;
    }




}


