package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Links generated by hbm2java
 */
public class Links  implements java.io.Serializable {


     private Integer linkId;
     private String linkName;

    public Links() {
    }

    public Links(String linkName) {
       this.linkName = linkName;
    }
   
    public Integer getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }
    public String getLinkName() {
        return this.linkName;
    }
    
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }




}


