package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Mcqs generated by hbm2java
 */
public class Mcqs  implements java.io.Serializable {


     private Integer id;
     private int questionId;
     private String answers;
     private String correctAnswer;

    public Mcqs() {
    }

	
    public Mcqs(int questionId) {
        this.questionId = questionId;
    }
    public Mcqs(int questionId, String answers, String correctAnswer) {
       this.questionId = questionId;
       this.answers = answers;
       this.correctAnswer = correctAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public String getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(String answers) {
        this.answers = answers;
    }
    public String getCorrectAnswer() {
        return this.correctAnswer;
    }
    
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }




}


