package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Integer programId;
     private Department department;
     private String programName;
     private Set<Course> courses = new HashSet<Course>(0);

    public Program() {
    }

    public Program(Department department, String programName, Set<Course> courses) {
       this.department = department;
       this.programName = programName;
       this.courses = courses;
    }
   
    public Integer getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(Integer programId) {
        this.programId = programId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getProgramName() {
        return this.programName;
    }
    
    public void setProgramName(String programName) {
        this.programName = programName;
    }
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


