package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * QuestionMcq generated by hbm2java
 */
public class QuestionMcq  implements java.io.Serializable {


     private Integer id;
     private String optionA;
     private String optionB;
     private String optionC;
     private String optionD;
     private String correct;
     private int questionId;

    public QuestionMcq() {
    }

    public QuestionMcq(String optionA, String optionB, String optionC, String optionD, String correct, int questionId) {
       this.optionA = optionA;
       this.optionB = optionB;
       this.optionC = optionC;
       this.optionD = optionD;
       this.correct = correct;
       this.questionId = questionId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOptionA() {
        return this.optionA;
    }
    
    public void setOptionA(String optionA) {
        this.optionA = optionA;
    }
    public String getOptionB() {
        return this.optionB;
    }
    
    public void setOptionB(String optionB) {
        this.optionB = optionB;
    }
    public String getOptionC() {
        return this.optionC;
    }
    
    public void setOptionC(String optionC) {
        this.optionC = optionC;
    }
    public String getOptionD() {
        return this.optionD;
    }
    
    public void setOptionD(String optionD) {
        this.optionD = optionD;
    }
    public String getCorrect() {
        return this.correct;
    }
    
    public void setCorrect(String correct) {
        this.correct = correct;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }




}


