package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private Integer questionId;
     private int levelId;
     private String question;
     private String questionText;
     private Date timeCreated;
     private Integer marks;
     private int typeId;

    public Questions() {
    }

	
    public Questions(int levelId, int typeId) {
        this.levelId = levelId;
        this.typeId = typeId;
    }
    public Questions(int levelId, String question, String questionText, Date timeCreated, Integer marks, int typeId) {
       this.levelId = levelId;
       this.question = question;
       this.questionText = questionText;
       this.timeCreated = timeCreated;
       this.marks = marks;
       this.typeId = typeId;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public int getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(int levelId) {
        this.levelId = levelId;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getQuestionText() {
        return this.questionText;
    }
    
    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }
    public Date getTimeCreated() {
        return this.timeCreated;
    }
    
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }
    public Integer getMarks() {
        return this.marks;
    }
    
    public void setMarks(Integer marks) {
        this.marks = marks;
    }
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }




}


