package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer id;
     private String statement;
     private Date dateCreated;
     private int difficultyLevel;
     private String questionType;
     private int marks;
     private int topicId;
     private int sectionId;
     private String courseId;
     private Integer quizId;

    public Question() {
    }

	
    public Question(String statement, Date dateCreated, int difficultyLevel, String questionType, int marks, int topicId, int sectionId, String courseId) {
        this.statement = statement;
        this.dateCreated = dateCreated;
        this.difficultyLevel = difficultyLevel;
        this.questionType = questionType;
        this.marks = marks;
        this.topicId = topicId;
        this.sectionId = sectionId;
        this.courseId = courseId;
    }
    public Question(String statement, Date dateCreated, int difficultyLevel, String questionType, int marks, int topicId, int sectionId, String courseId, Integer quizId) {
       this.statement = statement;
       this.dateCreated = dateCreated;
       this.difficultyLevel = difficultyLevel;
       this.questionType = questionType;
       this.marks = marks;
       this.topicId = topicId;
       this.sectionId = sectionId;
       this.courseId = courseId;
       this.quizId = quizId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatement() {
        return this.statement;
    }
    
    public void setStatement(String statement) {
        this.statement = statement;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getDifficultyLevel() {
        return this.difficultyLevel;
    }
    
    public void setDifficultyLevel(int difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }
    public String getQuestionType() {
        return this.questionType;
    }
    
    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }
    public int getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(int topicId) {
        this.topicId = topicId;
    }
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Integer getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }




}


