package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Questionlevel generated by hbm2java
 */
public class Questionlevel  implements java.io.Serializable {


     private Integer levelId;
     private String diificultyLevel;

    public Questionlevel() {
    }

    public Questionlevel(String diificultyLevel) {
       this.diificultyLevel = diificultyLevel;
    }
   
    public Integer getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }
    public String getDiificultyLevel() {
        return this.diificultyLevel;
    }
    
    public void setDiificultyLevel(String diificultyLevel) {
        this.diificultyLevel = diificultyLevel;
    }




}


