package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * QuizResult generated by hbm2java
 */
public class QuizResult  implements java.io.Serializable {


     private Integer id;
     private Integer quizSubmissionId;
     private Integer totakMarks;
     private Integer marksObtained;
     private Integer studentId;
     private String feedback;

    public QuizResult() {
    }

    public QuizResult(Integer quizSubmissionId, Integer totakMarks, Integer marksObtained, Integer studentId, String feedback) {
       this.quizSubmissionId = quizSubmissionId;
       this.totakMarks = totakMarks;
       this.marksObtained = marksObtained;
       this.studentId = studentId;
       this.feedback = feedback;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getQuizSubmissionId() {
        return this.quizSubmissionId;
    }
    
    public void setQuizSubmissionId(Integer quizSubmissionId) {
        this.quizSubmissionId = quizSubmissionId;
    }
    public Integer getTotakMarks() {
        return this.totakMarks;
    }
    
    public void setTotakMarks(Integer totakMarks) {
        this.totakMarks = totakMarks;
    }
    public Integer getMarksObtained() {
        return this.marksObtained;
    }
    
    public void setMarksObtained(Integer marksObtained) {
        this.marksObtained = marksObtained;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }




}


