package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * QuizQuestions generated by hbm2java
 */
public class QuizQuestions  implements java.io.Serializable {


     private Integer id;
     private int quizQuestionId;
     private int questionId;

    public QuizQuestions() {
    }

    public QuizQuestions(int quizQuestionId, int questionId) {
       this.quizQuestionId = quizQuestionId;
       this.questionId = questionId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuizQuestionId() {
        return this.quizQuestionId;
    }
    
    public void setQuizQuestionId(int quizQuestionId) {
        this.quizQuestionId = quizQuestionId;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }




}


