package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StudentNotification generated by hbm2java
 */
public class StudentNotification  implements java.io.Serializable {


     private int id;
     private String courseId;
     private String detail;
     private Date ndate;
     private Integer teacherId;

    public StudentNotification() {
    }

	
    public StudentNotification(int id) {
        this.id = id;
    }
    public StudentNotification(int id, String courseId, String detail, Date ndate, Integer teacherId) {
       this.id = id;
       this.courseId = courseId;
       this.detail = detail;
       this.ndate = ndate;
       this.teacherId = teacherId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Date getNdate() {
        return this.ndate;
    }
    
    public void setNdate(Date ndate) {
        this.ndate = ndate;
    }
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }




}


