package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * StudentRegistration generated by hbm2java
 */
public class StudentRegistration  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String courseId;

    public StudentRegistration() {
    }

    public StudentRegistration(int studentId, String courseId) {
       this.studentId = studentId;
       this.courseId = courseId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }




}


