package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private Integer userId;
     private String interest;
     private String background;
     private Integer departmentId;
     private String qualification;
     private String ranking;

    public Student() {
    }

    public Student(Integer userId, String interest, String background, Integer departmentId, String qualification, String ranking) {
       this.userId = userId;
       this.interest = interest;
       this.background = background;
       this.departmentId = departmentId;
       this.qualification = qualification;
       this.ranking = ranking;
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }
    public String getBackground() {
        return this.background;
    }
    
    public void setBackground(String background) {
        this.background = background;
    }
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getRanking() {
        return this.ranking;
    }
    
    public void setRanking(String ranking) {
        this.ranking = ranking;
    }




}


