package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * TeacherCourse generated by hbm2java
 */
public class TeacherCourse  implements java.io.Serializable {


     private Integer id;
     private int teacherId;
     private String courseId;

    public TeacherCourse() {
    }

    public TeacherCourse(int teacherId, String courseId) {
       this.teacherId = teacherId;
       this.courseId = courseId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }




}


