package model;
// Generated Jun 18, 2013 3:04:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Truefalse generated by hbm2java
 */
public class Truefalse  implements java.io.Serializable {


     private Integer id;
     private int questionId;
     private String trueAns;
     private String falseAns;

    public Truefalse() {
    }

	
    public Truefalse(int questionId) {
        this.questionId = questionId;
    }
    public Truefalse(int questionId, String trueAns, String falseAns) {
       this.questionId = questionId;
       this.trueAns = trueAns;
       this.falseAns = falseAns;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public String getTrueAns() {
        return this.trueAns;
    }
    
    public void setTrueAns(String trueAns) {
        this.trueAns = trueAns;
    }
    public String getFalseAns() {
        return this.falseAns;
    }
    
    public void setFalseAns(String falseAns) {
        this.falseAns = falseAns;
    }




}


